pmndrs/three-stdlib

- src/controls/PointerLockControls.ts
moves `direction: Vector3` out from `getDirection()` to be a private prop + removes what looked like a now unnecessary comment 
- [x ] Ready to be merged
> simplifies PointerLockControls.getDirection()

- .eslintrc.json
- src/controls/OrbitControls.ts
Fix existing errors in OrbitControls file
This was done as a follow-up to some peer feedback in another PR of mine (https://github.com/pmndrs/three-stdlib/pull/32#discussion_r593970348), and I figured it would be easier to enforce this at the lint level instead, just in case other contributors did something similar when copy-pasting existing examples.
> Add no-var eslint rule to enforce code style

- package.json
- yarn.lock
Clearly states if you use the `transform` plugin, you need to add `@babel/runtime` as a dependency. It was probably latching onto deps of other modules that do have it, see here: https://babeljs.io/docs/en/babel-plugin-transform-runtime#installation
> Add babel-runtime as dependency

- .storybook/stories/TransformControls.stories.ts
- package.json
- rollup.config.js
- scripts/createDeclarations.js
- src/controls/TransformControls.ts
- src/index.ts
- yarn.lock
only copies files that exist if we don't already have the file
Free .d.ts files while we move everything over!
runs a small script in node after build to find out which `.d.ts` files are missing and copy them over from `@types/three`
> Copy @three/types/examples at build time

- src/controls/OrbitControls.ts
This should be the only change needed in `three-stdlib` to close https://github.com/pmndrs/three-stdlib/issues/47. I'm following with another change in drei.
We don't want to pass domElement to MapControls as it causes a side effect — connects handlers to DOM.
This seems to be just a TypeScript adoption mishap, as OrbitControls's domElement parameter is correctly optional.
Made domElement constructor parameter optional.
> Make MapControls domElement parameter optional

- .storybook/stories/TransformControls.stories.ts
- src/controls/TransformControls.ts
Fixing issue [60#](https://github.com/pmndrs/three-stdlib/issues/60) 
As per the code of the original three js the visual feedback on the axes is managed simply by creating a couple of temporary variable for the colour and opacity.  See here :
https://github.com/mrdoob/three.js/blob/d39d82999f0ac5cdd1b4eb9f4aba3f9626f32ab6/examples/jsm/controls/TransformControls.js#L1528-L1532
The `_opacity` and `_color` are simply temp variable that suffered from a refactoring error in [this commit](https://github.com/pmndrs/three-stdlib/commit/cc079be1d2bb5f619202341a2fa53a4cb006056c)
> fix: #60 update transform controls axes visual feedback to match threejs

- .storybook/stories/Line.stories.ts
- demos/ssr/components/Line.tsx
- src/lines/LineMaterial.ts
The `useLayoutEffect` example to define `USE_DASH` isn't a very intuitive API. 
The `USE_DASH` define is automatically set and unset based on the dashed property.
There wasn't any documentation before for this as far as I can see, this makes it do the 'expected thing'. I've added a prop to the storybook to see it in action.
> Automatic enabling of USE_DASH define in lines

- src/lines/LineMaterial.ts
Resolves #44
The setter for the color builds a THREE.Color instance, which will consume any of the `ColorOptions` as specified in the types.
> fix: LineMaterial accepts THREE Colors

- src/lines/LineSegments2.ts
The raycast method for Line2 and LineSegments2 is current broken because it discards the value of the ray. It had been changed from the original implementation to satisfy the type checker, presumably.
This fix changes the implementation back to the original by using a type cast instead. You can see this branch follows the original implementation at https://github.com/mrdoob/three.js/blob/e8877dfb85ae017f53ef8d91237909bc162f524b/examples/jsm/lines/LineSegments2.js#L165
> Fix LineSegments2 raycaster

- src/controls/OrbitControls.ts
Enables a temporary fix for mobile pointer events in combination with how it's currenly wired in `drei`, see https://github.com/pmndrs/drei/issues/467 and https://github.com/pmndrs/drei/issues/470. Since `.connect` is called in [L968](https://github.com/pmndrs/three-stdlib/blob/main/src/controls/OrbitControls.ts#L968) anyway, it should behave the same as before if the `domElement` param is passed to the ctor. This is a stopgap measure until the [final API is settled](https://github.com/mrdoob/three.js/pull/21224#issuecomment-873099170).
> fix: move setting touchAction to .connect in orbit controls

- src/controls/OrbitControls.ts
> ### Why
> The camera needs to use the getDistance method in OrbitControls
> ### What
> 
> This is the PR for OrbitControls to increase the getDistance method.
> 
> ### Checklist
> * [ ]  Ready to be merged
> Added getDistance method to OrbitControls

- src/controls/OrbitControls.ts
When `getSecondPointerPosition` is called, **`pointers[0]` may be 'undefined'**.
> TypeError: undefined is not an object (evaluating 'Z[0].pointerId')
at getSecondPointerPosition(webpack://_N_E/../../.yarn/__virtual__/three-stdlib-virtual-9e9a05067f/0/cache/three-stdlib-npm-2.4.0-815db58d73-9d995e0146.zip/node_modules/three-stdlib/controls/OrbitControls.js:947:52)
at handleTouchMoveRotate(webpack://_N_E/../../.yarn/__virtual__/three-stdlib-virtual-9e9a05067f/0/cache/three-stdlib-npm-2.4.0-815db58d73-9d995e0146.zip/node_modules/three-stdlib/controls/OrbitControls.js:611:26)
at onTouchMove(webpack://_N_E/../../.yarn/__virtual__/three-stdlib-virtual-9e9a05067f/0/cache/three-stdlib-npm-2.4.0-815db58d73-9d995e0146.zip/node_modules/three-stdlib/controls/OrbitControls.js:883:11)
at …
> fix(card): change `addPointer` call line to before `addEventListener`

- src/exporters/USDZExporter.ts
This PR resolves #99. There was a problem creating USDZ files.
The problem was, that a curly bracket was in the wrong line.
The opening `{` has to be after the Material definition `def Material "Material" {`
> fix: curly bracket position in USDZExporter

- src/loaders/HDRCubeTextureLoader.js
- src/loaders/RGBELoader.js
- src/loaders/RGBMLoader.js
- src/nodes/core/NodeBuilder.js
- src/nodes/utils/ColorSpaceNode.js
- src/shaders/GammaCorrectionShader.ts
Fixes https://github.com/pmndrs/drei/issues/705 by mirroring changes made in the last release of three (r136), removing `RGBM7Encoding`, `RGBM16Encoding`, `RGBDEncoding`, `RGBEEncoding`, `RGBEFormat`, and `GammaEncoding`.
I think it's best for us to trim down to modules that we actually use and care to maintain, as these will continue to silently break as updates roll out to three without semver.
> fix: remove depreciated encodings with r136

- src/loaders/AMFLoader.js
- src/loaders/ColladaLoader.js
- src/loaders/EXRLoader.js
- src/loaders/FBXLoader.js
- src/loaders/GLTFLoader.js
- src/loaders/HDRCubeTextureLoader.js
- src/loaders/RGBELoader.js
- src/loaders/RGBMLoader.js
- src/loaders/SVGLoader.js
- src/loaders/VRMLLoader.js
My earlier fix in #108 wasn't enough since loaders were ancient and outdated. Pulled in affected loaders from three to ensure they're in sync.
> fix: pull loaders from upstream

- rollup.config.js
Running build generates a wall of text with hundreds of entries like:
```
Though the "loose" option was set to "true" in your @babel/preset-env config, it will not be used for @babel/plugin-proposal-private-property-in-object since the "loose" mode option was set to "false" for @babel/plugin-proposal-private-methods.
The "loose" option must be the same for @babel/plugin-proposal-class-properties, @babel/plugin-proposal-private-methods and @babel/plugin-proposal-private-property-in-object (when they are enabled): you can silence this warning by explicitly adding
["@babel/plugin-proposal-private-property-in-object", { "loose": false }]
to the "plugins" section of your Babel config.
```
Set the `loose` property to `false` for the plugin `@babel/plugin-proposal-private-property-in-object`
> chore: set private-property-in-object to loose: false

- src/controls/ArcballControls.ts
ArcballControls should not listen to keydown events and do clipboard actions by default (See #110)
Fixes #110 
- Removed keydown bindings
- copyState is now a public method
- pasteState is now a public method
> fix: remove keydown bindings for ArcballControls

- package.json
- src/exporters/GLTFExporter.ts
- src/utils/BufferGeometryUtils.ts
- yarn.lock
Validate that `three-stdlib` works with the latest version of `three.js`
- Update devDependency `@types/three` to `v0.137.0`
- Update devDependency `three` to `v0.137.4`
- Fixes #123
This does not bump the peerDependency version for `three.js`
> fix: Update devDependencies of three & @types/three to latest

- src/loaders/GLTFLoader.js
Removes usage of alphaWrite with https://github.com/mrdoob/three.js/commit/dfca2bd4748b00245225c9e4d8ba0ef7374c9b36#diff-c590b3c924c35c2f241746522284e4709df490d73a38aaa7d6de4ed1eac2f546 of r137.3.
> fix(GLTFLoader): remove alphawrite

- .github/ISSUE_TEMPLATE/---bug-report.md
We get bug reports like #123 where the types between `three` and `@types/three` do not match and cause confusion.
Added a prompt for `@types/three` to the bug report template.
> chore: prompt people to include their @types/three version

- package.json
#115 added usage of FramebufferTexture that was introduced in three r136, but did not bump the peerDependencies
Bumped the peerDependency of three to v0.137.0
Fixes #129
> minor: Update peerDependency of three to r137

- package.json
- yarn.lock
Chevrotain 10.1.1 did not include the src map files.  This was fixed in 10.1.2
bumped to chevrotain:10.1.2
- [x ] Ready to be merged
> fix: Bumped Chevrotain to 10.1.2 to fix missing missing src map files.

- package.json
- src/objects/Lensflare.js
Fixes #143.
Reverts the refactor of Lensflare made in #115 to loosen the three peer dep.
> fix(Lensflare): FramebufferTexture => Texture

- src/controls/DragControls.ts
`DragControls` in `three` has `getRaycaster` function
https://threejs.org/docs/index.html#examples/en/controls/DragControls
> chore: add `getRaycaster` for `DragControls`

- .storybook/stories/TransformControls.stories.ts
- src/controls/TransformControls.ts
The .reset() method of TransformControls was present in [three.js] but not in three-stdlib : 
.reset () : undefined
Resets the object's position, rotation and scale to when the current transform began. 
I wrapped it
> Adding the reset method to TransformControls

- src/exporters/STLExporter.ts
resolves #160 
The `scene.traverse` method receives an anonymous function as an argument that leads to `this` being undefined inside the function body. By using an arrow function we make sure that `this` references the upper scope class instance.
> fix: use arrow function in scene.traverse argument

- src/webxr/OculusHandModel.js
- src/webxr/XRHandMeshModel.js
XRHandMeshModel assumes a static folder layout of `/path/to/folder/[handedness].glb` whereas some users may prefer to load an absolute path from CDN.
This PR mirrors https://github.com/pmndrs/react-xr/pull/62, adding an absolute path arg to specify a custom model path. Also properly handles dispose for OculusHandModel.
> feat(XRHandMeshModel): add custom model path arg

- src/webxr/ARButton.ts
- src/webxr/VRButton.ts
The current ARButton and VRButton are not aligned with one another in allowing user-specified session init properties.
This PR allows session init to be specified in immersive-vr and converts both buttons to TS.
> feat(webxr): convert buttons to TS, passthrough vr sessioninit

- src/webxr/OculusHandModel.ts
- src/webxr/XRHandMeshModel.ts
Accepts separate args for left/right hands rather than an array, which can falsly break reference.
> fix(OculusHandModel): don't accept array

- .storybook/stories/BasicScene.stories.ts
- demos/ssr/components/Scene.tsx
- src/geometries/ConvexGeometry.js
- src/misc/ProgressiveLightmap.js
Deprecates usage of `*BufferGeometry` aliases since https://github.com/mrdoob/three.js/pull/24352.
> fix: deprecate usage of *BufferGeometry aliases

- package.json
The declaration files reference OffscreenCanvas, therefore it should be a dependency instead of a devDependency:
```
node_modules/three-stdlib/exporters/GLTFExporter.d.ts:41:75 - error TS2304: Cannot find name 'OffscreenCanvas'.
41 declare type ImageRepresentation = HTMLImageElement | HTMLCanvasElement | OffscreenCanvas | ImageBitmap;
~~~~~~~~~~~~~~~
```
Moved `@types/offscreen-canvas` to dependencies.
> fix(types): move @types/offscreencanvas to dependencies

- src/loaders/GLTFLoader.js
#190 introduces a regression where global `navigator` was not null-checked when profiling browser behavior.
> fix(GLTFLoader): play nice with headless environments

- src/loaders/GLTFLoader.js
Mirrors https://github.com/mrdoob/three.js/pull/24622, fixes https://github.com/mrdoob/three.js/issues/24799.
> fix(GLTFLoader): align attenuation

- src/animation/CCDIKSolver.js
Fixes https://github.com/pmndrs/three-stdlib/issues/197
Replace the old `Euler.toVector3()` with `Vector3.setFromEuler()`
> Replace old Euler.toVector3 with setFromEuler

- src/animation/CCDIKSolver.js
`scope` variable was missing
cf. https://github.com/mrdoob/three.js/blob/4f23d857b15b40fd5afd8a6bccaf761812efd70e/examples/js/animation/CCDIKSolver.js#L359
> fix(CCDIKHelper): missing var

- src/objects/Water2.js
fix "Uncaught ReferenceError: Water is not defined"
> fix(water2): fix water2 shader enum wrong.

- src/animation/CCDIKSolver.js
a third `sphereSize` optional parameter was introduced in 
https://github.com/mrdoob/three.js/pull/24652/files#diff-db84fa7e1e819602a1fa671dd94f7e6f0e0686e5cdb6ef8055a6aa5b921f9fda
> feat(CCDIKHelper): add `sphereSize` arg

- src/postprocessing/UnrealBloomPass.js
Following the fix for issue #207 the google closure compiler gives a warning about backslash line continuation. 
https://google.github.io/styleguide/jsguide.html#features-strings-no-line-continuations
It is not a bug, but it could easily lead to a bug in the future if left alone. A space after a backslash line continuation can cause strange issues.
I removed all the backslashes and replaced them with ' + instead.
After my changes the google closure compiler no longer gives warnings about this, but I am not sure if this change has any adverse effects on the codebase, though it shouldn't be a problem.
> fix: Removing backslash string line continuations

- src/renderers/CSS2DRenderer.js
Fixes #212 and adds backwards compat for https://github.com/mrdoob/three.js/pull/24028.
> fix: convert CSS2DRenderer to ES6, use new matrix flags

- src/libs/MotionControllers.ts
- src/webxr/XRControllerModelFactory.ts
Migrated vendored `MotionController` and `XRControllerModelFactory` to ts. I wasn't sure before, but now decided that it's better to continue with our own vendored version of these stuff, cause it'll allow us to push it further in terms of stability and feature-richness. Previous thoughts can be found below
> Right now it's a best-effort, and I'm not sure how to proceed. Main issue is that the issues why it was vendored in the first place was fixed since then and also typings improved, but new version haven't been released. I created an issue in the repo https://github.com/immersive-web/webxr-input-profiles/issues/224, but I'm not sure if we should just give up.
>
> The right way to do it would be to:
> * Use a new version of `@webxr-input-profiles/motion-controllers` with proper bundles …
> Migrated vendored motion controllers to ts

- src/webxr/XRControllerModelFactory.ts
It triggered a bug when controller were disconnecting (say from switching to hands or losing them). Controller group usually stayed the same but createControllerModel were called on each mount thus creating multiple listeners
createControllerModel now properly unsubscribes from controller group events
> fix: createControllerModel now unsubscribes from controller group events

- .prettierrc
This small change makes prettier not complain when opening CRLF files on Windows.
> Fix endOfLine error on Windows

- src/controls/OrbitControls.ts
resolves: https://github.com/pmndrs/three-stdlib/issues/219
In three.js , it sets state to none if the switch case does not match any MOUSE enum.
https://github.com/mrdoob/three.js/blob/dev/examples/jsm/controls/OrbitControls.js#L984
It would be nice to be able to omit the `mouseButtons` or `touches` elements.
Add Partial to `mouseButtons` and `touches` types in `OrbitControls`.
Thanks for the great package.
> fix: mouseButtons and touches allow undefined in OrbitControls

- src/loaders/GLTFLoader.js
Fixes a regression from https://github.com/pmndrs/three-stdlib/pull/226#issuecomment-1533805713 where uvs are not mapped according to material support in older versions of three.js. https://github.com/mrdoob/three.js/pull/25788 was also part of r152 so this isn't harmless.
> fix(GLTFLoader): add uv fallback

- src/loaders/KTX2Loader.js
Implements #229 based on https://github.com/mrdoob/three.js/pull/24745.
https://codesandbox.io/s/hbvbpy
> feat(KTX2Loader): add support for compressed arraytextures

- src/interactive/HTMLMesh.js
- src/lights/LightProbeGenerator.js
- src/loaders/3MFLoader.js
- src/loaders/EXRLoader.js
- src/loaders/FBXLoader.js
- src/loaders/GLTFLoader.js
- src/loaders/HDRCubeTextureLoader.js
- src/loaders/KTX2Loader.js
- src/loaders/RGBELoader.js
- src/misc/MD2Character.js
- src/misc/MD2CharacterComplex.js
- src/nodes/core/NodeBuilder.js
- src/nodes/display/ColorSpaceNode.js
- src/objects/Reflector.js
- src/objects/ReflectorForSSRPass.js
- src/objects/Refractor.js
- src/objects/Water2.js
- src/postprocessing/SSRPass.js
- src/renderers/webgpu/WebGPUTextures.js
Fixes #231 by hardcoding legacy encoding constants and rewriting to `colorSpace` and `outputColorSpace` where appropriate.
> fix: colorSpace <=> encoding fallback

- src/_polyfill/CompressedArrayTexture.js
- src/_polyfill/Data3DTexture.js
- src/loaders/KTX2Loader.js
- src/loaders/LUT3dlLoader.js
- src/loaders/LUTCubeLoader.js
- src/loaders/VOXLoader.js
- src/postprocessing/SSRPass.js
Polyfills `Data3DTexture` which was incorrectly consumed from three.js, breaking three < 138.
> fix: polyfill Data3DTexture

- src/libs/MeshoptDecoder.ts
Fixes #211 by rewriting `MeshoptDecoder` in TypeScript. Noting API from https://github.com/mrdoob/three.js/pull/24491 which is not available on NPM, I've compared it to latest or 0.19. Later, we should consume this from NPM if behavior didn't regress; the API didn't change.
> fix(MeshoptDecoder): rewrite in TypeScript for types export

- release.config.js
Fixes #239. We now build & publish in place instead of copying over to `dist`.
> chore: unblock release

- src/renderers/webgpu/WebGPURenderer.js
Fixes #244 by adding a file extension for explicit ESM rules. This will be superseded by #241.
> fix(WebGPURenderer): add explicit ext for glslang

- package.json
Fixes #251
Webpack 4 does not understand Node file extensions and is the only bundler to read from `module`. In a future major, we'll be able to utilize `package#exports` so ESM can resolve.
> fix: don't use Node ext for module field

- src/controls/OrbitControls.ts
Fixes #54
https://github.com/pmndrs/three-stdlib/commit/938045a3b77ccd9edb04064f2e0798bf721acbf8#diff-8a02d71e67deb0d9a2045fb5260a6a8298f3625ad8280ebb4f766aed9ca76707L94-R122 introduced a regression ignoring zoom for OrthographicCamera.
> fix(OrbitControls): respect zoom

- package.json
Removes `type=module` which is breaking CI. We don't need this yet as we don't use `package#exports` and Webpack 4 does not understand Node resolution generally.
> fix: remove type=module

- .codesandbox/ci.json
- package.json
- release.config.js
- yarn.lock
Adds back `private` to prevent commit spam from version bumps.
> fix: don't locally increment version

- src/webxr/OculusHandPointerModel.d.ts
- src/webxr/OculusHandPointerModel.js
Fixes an issue in `OculusHandPointerModel` where it would repeatedly create cursors on input change and create a memory leak. Additionally, I've implemented `dispose` to cleanup its listeners and to match the other WebXR classes.
> fix(OculusHandPointerModel): cleanup on disconnect, implement dispose

- src/utils/BufferGeometryUtils.ts
`BufferGeometryUtils.toCreasedNormals()` produces a warning by `BufferGeometry.toNonIndexed()` if the provided geometry is already non-indexed:
```
THREE.BufferGeometry.toNonIndexed(): BufferGeometry is already non-indexed.
```
It should not produce the warning.
resolves #268
This changes `BufferGeometryUtils.toCreasedNormals()` to call `BufferGeometry.toNonIndexed()` only if the provided geometry is indexed.
Otherwise, it will just use the original geometry, as has been the case before:
`BufferGeometry.toNonIndexed()` returns `this` if the geometry is non-indexed.
> fix(utils): `toCreasedNormals()`: call `toNonIndexed()` only on indexed geometries (#268)

- src/postprocessing/RenderPixelatedPass.d.ts
Hello,
The type declarations for RenderPixelatedPass does not appear to match the source file.
This PR is a quick manual fix for this. Although, other files may also need their types regenerated.
> fix(RenderPixelatedPass ): Types Mismatch

- src/webxr/OculusHandPointerModel.js
Mirrors https://github.com/mrdoob/three.js/pull/26387.
> fix(OculusHandPointerModel): safely dispose pointer mesh

- src/controls/OrbitControls.ts
OrbitControls only follows the object.up orientation on initialization, making it impossible to update if your controls has to follow an object walking around a geometry that's not a plane, such as a character walking around a planet. 
I've added two lines which updates the quat up direction inside the orbitcontrols.update method
This will add two unnecessary operations for most users, though. Perhaps it can be enabled by a flag?
> fix(OrbitControls): update camera up direction

- src/postprocessing/EffectComposer.ts
- src/postprocessing/SSAARenderPass.js
- src/postprocessing/SavePass.js
- src/postprocessing/TAARenderPass.js
- src/postprocessing/TexturePass.js
Fixes a regression since `BlendShader` and `CopyShader` expect use of premultiplied alpha.
> fix(postprocessing): use premult alpha

- src/controls/OrbitControls.ts
I'm trying to support drag controls that are different from what OrbitControls ships out of the box. The horizontal drag behaviour is what I want, but the vertical is inverted. Currently, we only have `reverseOrbit`, which enables the vertical drag behaviour that I want but inverts the horizontal as well.
`reverseHorizontalOrbit` is an API that enables inverting just the horizontal orbit direction.
`reverseVerticalOrbit` is an API that enables inverting just the vertical orbit direction.
update `rotateLeft` and `rotateRight` functions in `OrbitControls` to reflect new API.
> feat(OrbitControls): reverse horizontal and vertical orbits separately

- package.json
- vite.config.ts
- yarn.lock
Came across [this issue](https://github.com/Chevrotain/chevrotain/issues/1643) while developing a new nextjs project. It seems like the bundler does't find a default export from api.js. Chevrotain 11 is pure ESM, so there are only named exports, which means it shouldn't look for a default export at all.
```
./node_modules/chevrotain/lib_esm/api_esm.mjs
Attempted import error: '../lib/src/api.js' does not contain a default export (imported as 'mod').
Import trace for requested module:
./node_modules/chevrotain/lib_esm/api_esm.mjs
./node_modules/three-stdlib/loaders/VRMLLoader.js
./node_modules/three-stdlib/index.js
./node_modules/@react-three/drei/web/Select.js
./node_modules/@react-three/drei/index.js
./components/Graphic.tsx
```
Updated Chevrotain version to 11
> fix: update chevrotain

- package.json
- yarn.lock
Fixes #287. Partial revert of #284.
> fix: downgrade chevrotain for tree-shaking

- vite.config.ts
The `regexp-to-ast` must either be a production dependency, or inlined. I'm not sure I understand the tree-shaking implications of the last PR, or whether this should affect anything there.
Related:
- https://github.com/pmndrs/three-stdlib/pull/288
- https://github.com/pmndrs/three-stdlib/issues/287
> fix: Inline 'regexp-to-ast' dependency

- package.json
- vite.config.ts
- yarn.lock
Reverts #288 since #289 until downstream effects are better understood w/ESM.
> fix: revert chevotain

- src/exporters/GLTFExporter.js
Resolves #281 by dropping `FileReader.readAsArrayBuffer` and `FileReader.readAsDataURL` for `Blob.arrayBuffer` and `URL.createObjectURL`, respectively.
> refactor(GLTFExporter): prefer native Blob/URL methods

- package.json
- src/_polyfill/constants.ts
- src/controls/OrbitControls.ts
- src/libs/chevrotain.js
- src/loaders/GLTFLoader.js
- src/loaders/VRMLLoader.js
- src/objects/Reflector.js
- src/objects/Refractor.js
- src/objects/Sky.ts
- src/objects/Water2.js
- vite.config.ts
- yarn.lock
> fix: tree-shake chevrotain

- package.json
- src/libs/opentype.js
- src/loaders/TTFLoader.js
Opentype.js does not correctly configure Node ESM, so tree-shaking will not work when resolving as CJS.
> fix: vendor opentype as ESM

- src/controls/OrbitControls.ts
Orbit controls in three/examples has this line, it prevents text and other element selection on the screen when you drag camera. 
https://github.com/avaturn/three.js/blob/dev/examples/jsm/controls/OrbitControls.js#L979C4-L979C4
Added the line
> fix(OrbitControls): make use of setPointerCapture

- src/controls/experimental/CameraControls.ts
> experiment: enum => object

- src/controls/OrbitControls.ts
This is a breaking change that causes the presence of OrbitControls to break pointer events, if desired it should be released in a major. 
An alternative to reverting is making this opt-in via init options
- Reverts https://github.com/pmndrs/three-stdlib/pull/297
- Issue https://github.com/pmndrs/drei/issues/1675
> Revert "fix(OrbitControls): make use of setPointerCapture"

- .github/workflows/main.yml
- package.json
- vite.config.ts
- yarn.lock
> experiment: preserve modules

- src/objects/BatchedMesh.ts
Fixes #310 by moving the usage of member properties for render hooks to the constructor.
> fix(BatchedMesh): move render hooks to constructor for dts

- src/exporters/GLTFExporter.js
Fixes #312 from a regression since #282.
> fix(GLTFExporter): return populated json

- src/renderers/CSS3DRenderer.js
Mirrors https://github.com/mrdoob/three.js/pull/27017 which prefers `transform: perspective(FOVpx)` to `perspective: FOVpx` due to browser 3D rendering issues.
> fix(CSS3DRenderer): modify perspective transform to avoid browser issues

- src/controls/OrbitControls.ts
When `matrixAutoUpdate` is false, the `lookAt` does not get the correct matrix and the target is delayed. This PR calls a manual `matrixUpdate` if `matrixAutoUpdate` is false.
> fix(OrbitControls): update lookAt when matrixAutoUpdate false

- src/postprocessing/ShaderPass.ts
- src/shaders/types.ts
The types have errors when used with @types/three@0.160.0, because [the `Shader` type was removed in @types/three@0.160.0](https://github.com/three-types/three-ts-types/releases/tag/r160) due it it being used in ways it wasn't intended to be used. The type errors are:
```
Error: ./node_modules/three-stdlib/postprocessing/ShaderPass.d.ts(1,10): error TS2305: Module '"three"' has no exported member 'Shader'.
Error: ./node_modules/three-stdlib/shaders/types.d.ts(1,25): error TS2305: Module '"three"' has no exported member 'Shader'.
```
Remove use of the `Shader` type with more suitable types.
> fix(types): remove references to Shader type

- src/loaders/EXRLoader.js
Fixes #318. Mirrors https://github.com/mrdoob/three.js/pull/24049.
> fix(EXRLoader): support longname flag

- src/controls/ArcballControls.ts
- src/controls/DeviceOrientationControls.ts
- src/controls/DragControls.ts
- src/controls/FlyControls.ts
- src/controls/OrbitControls.ts
- src/controls/PointerLockControls.ts
- src/controls/TrackballControls.ts
- src/controls/TransformControls.ts
- src/controls/experimental/CameraControls.ts
- src/loaders/FontLoader.ts
- src/loaders/HDRCubeTextureLoader.d.ts
- src/loaders/HDRCubeTextureLoader.js
- src/modifiers/CurveModifier.ts
- src/modifiers/TessellateModifier.ts
- src/postprocessing/BloomPass.ts
- src/postprocessing/DotScreenPass.ts
- src/postprocessing/FilmPass.ts
- src/postprocessing/GlitchPass.ts
- src/postprocessing/WaterPass.ts
- src/webxr/OculusHandModel.ts
Fixes #323 Related: https://github.com/pmndrs/drei/pull/1765
> fix(types): three r160 breaking changes

- src/lines/LineGeometry.js
- src/lines/LineMaterial.js
- src/lines/LineSegmentsGeometry.d.ts
- src/lines/LineSegmentsGeometry.js
Continues #92. Vertex colors chunks were incorrectly re-used for its varying, but not actually multiplied.
> feat(Lines): alpha support for line color

- src/lines/LineSegmentsGeometry.js
Continues #335. Correctly sets interleave offset dynamically with function call.
> fix(LineSegmentsGeometry): dynamic interleave offset

- src/lines/LineMaterial.js
Fixes #337 where unset vertex colors would multiply with their zeroed or unset values.
https://codesandbox.io/p/sandbox/vigorous-tesla-p8jjct
> fix(LineMaterial): don't multiply unset vertexColors

- src/loaders/HDRCubeTextureLoader.js
According to three.js version 0.152 [migration guide](https://github.com/mrdoob/three.js/wiki/Migration-Guide), Texture.encoding has been replaced with Texture.colorSpace with THREE.NoColorSpace as the default value 
Fixed warning logged in console "THREE.Texture: Property .encoding has been replaced by .colorSpace."
> fix(HDRCubeTextureLoader): colorSpace <=> encoding fallback

- src/objects/Reflector.d.ts
- src/objects/Refractor.d.ts
- src/objects/Water2.d.ts
- src/types/shared.ts
[`TextureEncoding` was removed in r162](https://github.com/three-types/three-ts-types/releases/tag/r162).
Stub the `TextureEncoding` type to avoid a breaking change.
> fix(types): stub TextureEncoding

- src/animation/MMDPhysics.d.ts
- src/controls/OrbitControls.ts
- src/utils/RoughnessMipmapper.d.ts
The ambient THREE namespace was [removed in `@types/three@0.162.0`](https://github.com/three-types/three-ts-types/releases/tag/r162).
Removes usages of the ambient THREE namespace.
> fix(types): fix usages of ambient THREE namespace

- src/loaders/KTX2Loader.d.ts
resolves #345
Removed the erroneous "parse" method from KTX2Loader.d.ts
> fix(KTX2Loader): remove parse overload from types

- src/loaders/VRMLLoader.js
Three.js AxisAngle apparently requires a normalized axis vector.  VRML may also, but I had many files (converted from VRML 1.0) that contained un-normalized axis vectors.
Whether there is a defect in my VRML data or not, normalization is idempotent and can only help.
I added `.normalize()` to the axis vector for a rotation in VRMLLoader.js.
> Fixed rotation defect in VRMLLoader.js

- src/controls/OrbitControls.ts
When connecting to the OrbitControl, we set `touchAction` to none, which prevents the user from scrolling the page and allows them to interact with the 3D scene. However, when we dispose of the OrbitControl, we don't re-enable the `touchAction`, which means the user is unable to scroll the page even after the OrbitControl is disabled or removed.
There are situations where we want to allow users to interact with the scene when they click a button, but in other cases, we don't want them to interact, and instead, allow them to scroll the page. However, if we set the `touchAction` to `none` and don't re-enable it after disposing of the OrbitControl, the user will be unable to scroll the page at all.
In `this.dispose` method, I set `touchAction` to `auto`
>  Enabling touchAction when `this.dispose` is called.

- src/controls/OrbitControls.ts
Resolves: https://github.com/pmndrs/three-stdlib/issues/352
> fix(OrbitControls): make "wheel" listener passive

- src/controls/OrbitControls.ts
Uses https://github.com/mrdoob/three.js/pull/25540/files to fix https://github.com/mrdoob/three.js/issues/25505
> fix(OrbitControls): upstream fixes

- src/exporters/USDZExporter.ts
When applying a texture with a transparent background, the USDZ exporter doesn't export the transparency of the texture. In this PR it will fix it.
I changed the shader of the USDZ exporter to include the `opacity` as `alpha` and `opacityThreshold`. The applied changes are based of the Pull request in THREE,js [USDZExporter: Support opacity materials](https://github.com/mrdoob/three.js/pull/23588). It looks like this change later was removed from the source code again. I reimplemented it in this code base with an additional step to always include an `opacityThreshold` of `0.01` when the material is transparent since it will show a white blur if not.
> fix(USDZExporter): alpha issues in diffuse map

- src/_polyfill/LoaderUtils.js
- src/loaders/3MFLoader.js
- src/loaders/AMFLoader.js
- src/loaders/FBXLoader.js
- src/loaders/GLTFLoader.js
- src/loaders/PCDLoader.js
- src/loaders/PLYLoader.js
- src/loaders/STLLoader.js
- src/loaders/VTKLoader.js
- src/loaders/XLoader.js
Vendors `LoaderUtils.decodeText` with the deprecation of https://github.com/mrdoob/three.js/pull/28278.
We use this over `TextDecoder` to play nice with Node, react-native, and edge environments where browser APIs are limited.
> fix(loaders): vendor decodeText for r165 deprecation

- src/loaders/KTX2Loader.js
The web workers created by KTX2Loader throw the following error: `Uncaught ReferenceError: _KTX2Loader is not defined`.
This PR fixes that.
Updated the `BasisWorker` function to reference the variables that are prepended to the web worker code instead of referencing these values from the `KTX2Loader` class.
Although the `BasisWorker` function is defined within the `KTX2Loader` class, once it's stringified and used as code for a web worker it doesn't have access anymore to its original upper scope. Therefore it will throw an `ReferenceError`.
JSDoc type annotations have been added to get the right type hinting in the `BasisWorker` code.
Fixes:
- https://github.com/pmndrs/drei/issues/1860
> fix(KTX2Loader): web worker scope

- src/deprecated/Geometry.d.ts
The `Matrix` interface was removed in [@types/three@0.167.0](https://github.com/three-types/three-ts-types/releases/tag/r167). `Matrix4` seems like the better type anyway.
Replace use of `Matrix` interface with `Matrix4`.
> fix(types): compatibility with @types/three@0.167.0

- src/lines/LineMaterial.js
- src/lines/LineSegments2.js
- src/lines/Wireframe.js
Update `Line2` to match a few newer changes from `threejs`.
- https://github.com/mrdoob/three.js/pull/25032
- https://github.com/mrdoob/three.js/pull/28343
> feat: remove need for manually assigning Line2 material resolution

- src/controls/ArcballControls.ts
- src/controls/FirstPersonControls.ts
> feat: refactor control classes to use readonly for target property

- src/_polyfill/uv1.ts
- src/exporters/ColladaExporter.ts
- src/lines/LineSegments2.js
- src/loaders/ColladaLoader.js
- src/loaders/FBXLoader.js
- src/loaders/LWOLoader.js
- src/misc/ProgressiveLightmap.js
- src/modifiers/TessellateModifier.ts
`uv2` has been renamed to `uv1` in `threejs`: https://github.com/mrdoob/three.js/pull/25943
> fix: BufferGeometry rename uv2 to uv1

- src/shaders/GammaCorrectionShader.ts
Add support for sRGBTransferOETF to fix the runtime error below.
```
THREE.WebGLProgram: Shader Error 0 - VALIDATE_STATUS false
Material Name: 
Material Type: ShaderMaterial
Program Info Log: Fragment shader is not compiled.
FRAGMENT
ERROR: 0:173: 'LinearTosRGB' : no matching overloaded function found
ERROR: 0:173: '=' : dimension mismatch
ERROR: 0:173: 'assign' : cannot convert from 'const mediump float' to 'out highp 4-component vector of float'
168: 
169: uniform sampler2D tDiffuse;
170: varying vec2 vUv;
171: void main() {
172: 	vec4 tex = texture2D( tDiffuse, vUv );
> 173: 	gl_FragColor = LinearTosRGB( tex );
174: }
```
> fix: Add support for sRGBTransferOETF to fix the runtime error `'LinearTosRGB' : no matching overloaded function found`

- src/controls/OrbitControls.ts
It's really necessary to programmatically control the zoom scale in OrbitControls. Not only do my projects need this but many others may want this, too.
https://stackoverflow.com/questions/43167656/programmatically-zoom-orbitcontrols
https://stackoverflow.com/questions/39856907/three-js-orbitcontrols-js-invoking-zoom-in-out-with-button-controls-dollyout
https://stackoverflow.com/questions/41198618/orbitcontrols-js-how-to-zoom-in-zoom-out
I added a few methods to perform the dolly operations, and programmatically control the actual zoom scale. These are not used in most scenarios, however they can be useful for specific use cases
```ts
// Not used in most scenarios, however they can be useful for specific use cases
getZoomScale: () => number
// Dolly in programmatically
dollyIn: …
```
> feat(OrbitControls): expose zoom methods for programmatical controls

- src/controls/ArcballControls.ts
- src/controls/DeviceOrientationControls.ts
- src/controls/DragControls.ts
- src/controls/EventDispatcher.ts
- src/controls/FirstPersonControls.ts
- src/controls/FlyControls.ts
- src/controls/OrbitControls.ts
- src/controls/PointerLockControls.ts
- src/controls/StandardControlsEventMap.ts
- src/controls/TrackballControls.ts
- src/controls/experimental/CameraControls.ts
> fix: controls event dispatcher types

- src/helpers/RaycasterHelper.ts
As discussed with @gsimone, I'm relocating his [`RaycasterHelper`](https://github.com/gsimone/things/tree/main/packages/three-raycaster-helper) class here:
> feat: `RaycasterHelper`

- src/postprocessing/Pass.ts
- src/utils/ShadowMapViewer.d.ts
The `Renderer` interface [was removed](https://github.com/three-types/three-ts-types/pull/1487) in [@types/three@0.172.0](https://github.com/three-types/three-ts-types/releases/tag/r172). This PR removes usages so that `three-stdlib` works with @types/three@0.172.0.
Replace uses of `Renderer` with `WebGLRenderer`.
> fix: type compatibility with @types/three@0.172.0

- src/objects/Lensflare.js
Fixes #396 where three.js will no longer allocate GPU storage for textures when using framebuffer  copy methods unless they follow the `FramebufferTexture` signature, so nothing of Lensflare will render.
> fix(Lensflare): implement framebuffer texture for GPU storage

- patch-ts.js
Bug introduced in #343, which was a fix for #342.
Closes #399
Fix incorrect dist syntax from `export * type from` -> `export type * from`
/cc @bundyfx @CodyJasonBennett 
I'd prefer @CodyJasonBennett review
> fix `export * type` to `export type *` in patch-ts

- src/libs/lottie.js
When used on server side or test runner (without any bundling), it cause this kind of error even though I'm using SVGRenderer instead of the default renderer.
```js
Error: 
at <anonymous> (/home/runner/work/circuit-to-svg/circuit-to-svg/node_modules/three-stdlib/libs/lottie.js:1052:7)
at <anonymous> (/home/runner/work/circuit-to-svg/circuit-to-svg/node_modules/three-stdlib/libs/lottie.js:1054:14)
at <anonymous> (/home/runner/work/circuit-to-svg/circuit-to-svg/node_modules/three-stdlib/libs/lottie.js:1248:12)
at /home/runner/work/circuit-to-svg/circuit-to-svg/node_modules/three-stdlib/libs/lottie.js:13924:10
1047 |     var proxyImage = function() {
1048 |       var canvas = createTag("canvas");
1049 |       canvas.width = 1;
1050 |       canvas.height = 1;
1051 |       var ctx = …
```
> fix: error when used on server side via SVGRenderer

- src/exporters/GLTFExporter.js
resolves #407 
syncing [this fix](https://github.com/mrdoob/three.js/commit/a7712cc3a0902f2c45e919a811622ed72ad5f5de) into the library's current implementation. And after local testing, it works fine.
> fix: Fix alignment of integer vertex attributes

- src/postprocessing/GlitchPass.ts
- src/postprocessing/SSAOPass.js
Closes #418 with the removal of `LuminanceFormat` since https://github.com/mrdoob/three.js/pull/30934.
> fix: remove use of WebGL1 LuminanceFormat
