pmndrs/three-stdlib

package.json
src/animation/MMDAnimationHelper.js
src/exporters/GLTFExporter.js

Change consts to let

---

src/curves/NURBSUtils.ts

`FBXLoader` for https://github.com/pmndrs/three-stdlib/issues/10 depends on `NURBSCurve`, which depends on `NURBSUtils` 
- Converts NURBSUtils.js -> NURBSUtils.ts
- adds types where I could
- Converts comments to JSDoc for IDE previewing

refactor: NURBSUtils.js -> NURBSUtils.ts

---

.prettierignore
demos/ssr/components/Controls.tsx
demos/ssr/next.config.js
demos/ssr/package.json
demos/ssr/tsconfig.json
demos/ssr/yarn.lock
src/loaders/TiltLoader.js

`three-stdlib` should work with SSR ootb, resolves #18
`TiltLoader` called `DataTexture` in the file without being wrapped in a function, this has been resolved. CodeSandbox demo shows SSR working with the library.

[v1] SSR handling

---

.eslintrc.json
src/controls/DeviceOrientationControls.ts
src/controls/DragControls.ts
src/controls/FirstPersonControls.ts
src/controls/FlyControls.ts
src/controls/PointerLockControls.ts
src/controls/TrackballControls.ts
src/controls/TransformControls.ts
src/lines/Line2.ts
src/lines/LineGeometry.ts
src/lines/LineMaterial.ts
src/lines/LineSegments2.ts
src/lines/LineSegmentsGeometry.ts
src/math/SimplexNoise.ts
src/modifiers/CurveModifier.ts
src/modifiers/EdgeSplitModifier.ts
src/modifiers/SimplifyModifier.ts
src/modifiers/TessellateModifier.ts
src/objects/Sky.ts
src/postprocessing/EffectComposer.ts
src/postprocessing/MaskPass.ts
src/postprocessing/Pass.ts
src/postprocessing/ShaderPass.ts

Add https://github.com/typescript-eslint/typescript-eslint/blob/v4.15.2/packages/eslint-plugin/docs/rules/explicit-member-accessibility.md to the codebase.
I left out constructor methods since those are pretty much always public.

Add explicit member accessibility in eslint

---

src/postprocessing/RenderPass.ts

Move RenderPass into a TypeScript class def

---

src/lines/LineGeometry.ts
src/lines/LineSegmentsGeometry.ts

Proposed fix for https://github.com/pmndrs/three-stdlib/issues/41

move LineGeometry methods from instance to prototype methods

---

src/webxr/XRControllerModelFactory.js

There's a typo mentioning a package that doesn't exist
Use appropriate package that's already in package.json

fix: use correct package name

---

src/loaders/TiltLoader.js

Fix SSR issue introduced in last version
- [x ] Ready to be merged

Fix ssr tiltloader

---

.storybook/setup.ts
.storybook/stories/OrbitControls.stories.ts
.storybook/stories/TransformControls.stories.ts
src/controls/OrbitControls.ts

Added additional setters to `OrbitControls` that allow setting the polar / azimuthal angles directly. This allows for programmatic control like:
```ts
// ...
const myCamera = useRef<PerspectiveCamera>();
const controls = useRef<OrbitControls>();
useFrame(() => {
const angle = 0.42; // get current value from whatever (animation) state
controls.current?.setAzimuthalAngle(angle);
}, 1);
return (
<>
<OrbitControls enabled={false} camera={myCamera.current} ref={controls} />
<PerspectiveCamera ref={myCamera} position={[0, 5, 5]} />
</>
);
```
This "quick & dirty" implementation is based on a code snippet from @drcmda to always converts to the shortest delta angle give the current position. Would appreciate some eyes as this might be yet simplified, but it did the job for me so far.

Expose direct polar/azimuthal angle controls

---

src/controls/DragControls.ts
src/controls/FirstPersonControls.ts
src/controls/FlyControls.ts
src/controls/OrbitControls.ts
src/controls/TrackballControls.ts

Same changes as per https://github.com/mrdoob/three.js/pull/21935

Controls: Remove preventDefault() from mouse handlers

---

src/controls/OrbitControls.ts

Brings orbit controls up to date after
https://github.com/mrdoob/three.js/pull/21972

chore: refactor orbit controls to pointer events

---

src/custom.d.ts
src/exporters/MMDExporter.ts

Part of #12 
This is a PR of `MMDExporter` migration to TypeScript.

refactor: move `MMDExporter` into TypeScript

---

src/exporters/STLExporter.js
src/exporters/STLExporter.ts

Part of #12 
This is a PR of `STLExporter` migration to TypeScript.

refactor: move `STLExporter` into TypeScript

---

src/exporters/PLYExporter.js
src/exporters/PLYExporter.ts

Part of #12 
This is a PR of `PLYExporter` migration to TypeScript.

refactor: move `PLYExporter` into TypeScript

---

src/csm/Shader.js

Fix broken CSM module
- Sync changes from https://github.com/mrdoob/three.js/commits/dev/examples/jsm/csm
- Fix pkg main/module path
- Only include dist when publishing to npm

fix: update CSM shader

---

src/controls/OrbitControls.ts

fix: orbit controls stickiness regression

---

src/controls/TrackballControls.ts

feat: cursor zoom

---

src/controls/ArcballControls.ts

When trying to implement storybook entries for the ArcballControls in drei, I realized that updating the props was not having an effect.
- I'm not sure why the connect method was removed in the last change, but I restored it.
- Removed all `instanceof` checks for the camera and made the accepted Camera type explicit.
- Removed some unused private methods & unused properties

Add connect method to ArcballControls

---

src/controls/TransformControls.ts

Transform Controls has a side effect in the constructor. We want to avoid that and continue the work started on the other controls. In addition that allows us to change the target domElement on the fly.
https://github.com/mrdoob/three.js/issues/20575#issue-731834158
* Created a `connect` method and attach there all the dom event that were attached in the constructor.
* Adjust typings to make domElement option in the constructor and in the class.

feature: make transform-controls side-effect free

---

.storybook/stories/PointerLock.stories.ts

Added a story for pointer lock controls

fix: add story for PLC

---

.storybook/stories/FirstPersonControls.stories.ts
src/controls/FirstPersonControls.ts

I'm looking at adding `.connect(domElement)` methods to all of the controls so that we don't have side-effects in our constructors.
Starting with `FirstPersonControls`
- window eventListeners moved into connect
- Added connect call to the story

feat: add connect method to FirstPersonControls

---

src/loaders/GLTFLoader.js

Fix, removed an RGBFormat left.

fix: GLTFLoader forgot to remove RGBFormat

---

package.json
yarn.lock

Fixes #133 
Update chevrotain from v9.0.2 to v10.1.1

Update chevrotain from v9.0.2 to v10.1.1

---

.storybook/stories/Line.stories.ts
src/utils/GeometryUtils.ts

Looks like it doesn't `GeometryUtils`, just export `hilbert3D`, `gosper` and `hilbert2D`
Convert `GeometryUtils ` to TS and exporting `GeometryUtils`

fix: export `GeometryUtils`

---

src/webxr/OculusHandModel.ts
src/webxr/XRHandMeshModel.ts

Adds TS definitions to #162 since they deviate from three.

fix(webxr): convert to TS

---

src/geometries/ParametricGeometries.js
src/geometries/ParametricGeometry.js

Fixes #178 by vendoring `ParametricGeometry` into examples.

fix(ParametricGeometries): vendor ParametricGeometry

---

src/interactive/InteractiveGroup.js

Fixes #170. Needed if converting the three sandbox example to another framework.
Adding interactive/InteractiveObject.js

feat(interactive): adding InteractiveObject

---

src/interactive/InteractiveGroup.js

Lints changes from https://github.com/pmndrs/three-stdlib/pull/171.

chore: lint

---

src/geometries/ConvexGeometry.js
src/math/ConvexHull.js

fix(ConvexGeometry): support clone

---

src/loaders/GLTFLoader.js

Updates GLTFLoader with [upstream changes](https://github.com/mrdoob/three.js/compare/dfca2bd4748b00245225c9e4d8ba0ef7374c9b36..223c5721f2c5e6a13f17de8dfe0ea61ed8465ff0#diff-868e3d9b3219d163d7d53939fc3f7a6e65b7664ad5e3da03cd31fa23ea1a6df6).

feat(GLTFLoader): emissive strength, iridescence, morph colors

---

src/textures/FlakesTexture.ts

Fixes https://github.com/pmndrs/three-stdlib/issues/198
Transform FlakesTexture into ts file.

turn FlakesTexture into ts file

---

src/helpers/LightProbeHelper.js
src/helpers/PositionalAudioHelper.js
src/helpers/RectAreaLightHelper.js

Fixes #204 by removing invalid usage of `this` before calls to `super`.

fix(helpers): don't use this before construction

---

.prettierrc
src/misc/Timer.ts

This PR adds Mugen's `Timer` from: https://github.com/mrdoob/three.js/pull/17912
It is a huge upgrade to `Clock` and something we want to start building our own scheduler off of.

Feat: Add Timer

---

src/loaders/GLTFLoader.js

Resolves https://github.com/pmndrs/react-three-fiber/issues/2848 by updating `GLTFLoader` with three.js.

fix(GLTFLoader): upstream with three

---

src/loaders/GLTFLoader.js

Reverts https://github.com/mrdoob/three.js/pull/25236
Fixes https://github.com/pmndrs/drei/issues/1449

fix(GLTFLoader): revert use of TextDecoder

---

vite.config.ts

fix: restore config

---

src/controls/TrackballControls.ts

feat(TrackballControls): expose target

---

vite.config.ts

Adds on to #254 so builds' extensions match.

fix: rebuild

---

package.json

Ensures content displays correctly on NPM.

fix: add missing meta files to build

---

src/_polyfill/CapsuleGeometry.js
src/animation/MMDPhysics.js
src/exporters/GLTFExporter.js

Ensures compatibility with r128 since recent regressions.

fix: compat

---

src/loaders/SVGLoader.d.ts

fix: SVGLoader accepts Vector3

---

src/controls/OrbitControls.ts

Implements #285 with later fixes.

feat(OrbitControls): zoomToCursor

---

src/exporters/GLTFExporter.js

Addresses a regression from https://github.com/pmndrs/three-stdlib/issues/287#issuecomment-1734879561.

fix(GLTFExporter): hoist static methods

---

src/libs/lottie.js

Fixes a regression since #298.

fix: SSR w/lottie

---

.github/workflows/main.yml

Adds preliminary integration tests for common publishing issues.

chore: integration tests

---

src/exporters/GLTFExporter.js

Mirrors https://github.com/mrdoob/three.js/pull/26909.

feat(GLTFExporter): add support for 4 uv channels

---

src/objects/BatchedMesh.ts

Mirrors https://github.com/mrdoob/three.js/pull/27043.

fix(BatchedMesh): use zero-scale matrix for visibility

---

src/objects/BatchedMesh.ts

Upstreams fixes and improvements from https://github.com/mrdoob/three.js/pull/27060, https://github.com/mrdoob/three.js/pull/27066, https://github.com/mrdoob/three.js/pull/27074, https://github.com/mrdoob/three.js/pull/27077, https://github.com/mrdoob/three.js/pull/27078, https://github.com/mrdoob/three.js/pull/27099.

fix(BatchedMesh): upstream fixes

---

src/controls/OrbitControls.ts

fix(OrbitControls): orthographic zoom update

---

src/_polyfill/CompressedCubeTexture.js
src/loaders/KTX2Loader.js

fix(KTX2Loader): mips, cube, p3

---

src/loaders/RGBELoader.js

Mirrors https://github.com/mrdoob/three.js/pull/26742 and https://github.com/mrdoob/three.js/pull/26499.

fix(RGBELoader): upstream fixes

---

src/loaders/SVGLoader.js

NOTE: https://github.com/mrdoob/three.js/pull/23392 is future compatible, so we can call it in older three versions without feature checks.

fix(SVGLoader): upstream fixes

---

src/controls/OrbitControls.ts

fix(OrbitControls): don't preventDefault in wheel

---

src/controls/OrbitControls.ts

Reverts #353 and #360 due to a regression in document behavior.

fix(OrbitControls): revert passive wheel

---

src/loaders/GLTFLoader.js

Uses upstream improvements for glTF dispersion https://github.com/mrdoob/three.js/pull/28051.
Also includes: https://github.com/mrdoob/three.js/pull/28226, https://github.com/mrdoob/three.js/pull/27877, https://github.com/mrdoob/three.js/pull/27306, https://github.com/mrdoob/three.js/pull/27036, https://github.com/mrdoob/three.js/pull/27106, https://github.com/mrdoob/three.js/pull/26559, https://github.com/mrdoob/three.js/pull/26854
https://codesandbox.io/p/sandbox/goofy-rain-m55s4q

feat(GLTFLoader): dispersion

---

src/math/Lut.js
src/objects/Reflector.js
src/objects/Refractor.js

fix: use correct value for LinearSRGBColorSpace

---

.github/workflows/main.yml

Upgrade Node version for picocolors/publint quality checks from 14.

chore(CI): upgrade Node

---

.github/workflows/main.yml
release.config.js

chore: upgrading semantic-release

---

src/shaders/ACESFilmicToneMappingShader.ts
src/shaders/FXAAShader.ts
src/shaders/GodRaysShader.ts
src/shaders/ParallaxShader.ts
src/shaders/VignetteShader.ts

fix: syntax errors in shaders

---

src/controls/PointerLockControls.ts

Same as https://github.com/mrdoob/three.js/pull/30966

feat(PointerLockControls): Constant for mouse sensitivity
